### ISSUE TITLE
screen shoot my consol

### ISSUE THREAD

**Issue by ZIKO94ZIKO** [JdeRobot/traffic-monitor#3]
HI Sir , merci pour rendre ce project opensource pouvez vous  m'expliquer pourquoi il reste bloquer ici : 
![Screenshot from 2019-11-01 14-24-47](https://user-images.githubusercontent.com/52079137/68027745-75f75600-fcb3-11e9-9a40-f71e56538a7d.png)

**Comment by ZIKO94ZIKO** [comment]
lah yhfdek akhoya  3awni 3andi sujet bhalo f pfe mazal m3reftch kifach ndir RUN

**Comment by rkachach** [comment]
This was caused with some unknown issue with the user's environment. After installing a fresh env the issue disappeared. I'm closing the issue.
