### ISSUE TITLE
screenshot or capture video of each car

### ISSUE THREAD

**Issue by zongoalbert** [JdeRobot/traffic-monitor#4]
how can be do screenshot for cars  (speed > 100 km/h) without blur  in real time ,and save them in path/imagX.png

**Comment by zongoalbert** [comment]
I tried  to add the function `imwrite("/path/image",output)` in file `viewgtk.cpp` line 312 , it's work but the result of image is blur like this image
![04-12-2019 18-55-40](https://user-images.githubusercontent.com/55978810/70548266-8af8bc00-1b72-11ea-8380-720d177a2473.png) , any idea to improve quality of images + remove the blur ,

**Comment by rkachach** [comment]
I don't know why you get this blurry image since I don't know what's the resolution of the original video you used etc, so I'm afraid that I can't answer your question. To get a good image you have to use a high definition video source and make sure the whole pipeline maintains this resolution (including your cropping code).

**Comment by zongoalbert** [comment]
HI Sir , thank you for your answer , the resolution of  the original video used is 4k , i downloaded  this videofrom youtube  : [https://www.youtube.com/watch?v=uQa8EykTDkE](url)  .I used the some cropped used in function   `draw_vehicle_rear`  and  i removed the lines (381-383) in file `viewgtk.cpp` for detecting all vehicles . i tested the functions  filter2DFreq() in opencv [https://docs.opencv.org/master/d1/dfd/tutorial_motion_deblur_filter.html](url) to improve the quality of image , but also  not work well .

**Comment by rkachach** [comment]
The draw_rear_vehicle performs a simple rectification (https://en.wikipedia.org/wiki/Image_rectification). And it just uses small 128x96 image (see defines below): 

```
void ViewGtk::draw_vehicle_rear(Vehicle* vehicle)
  {
    if (vehicle)
    {
#define WITDH 96
#define HEIGHT 128
      Tpoint2D e,f,g,h;
      ....
````

that's why  you get small and blurry images. In order to crop the vehicle correctly you have to introduce your own code to do it instead of using this function.

**Comment by zongoalbert** [comment]
Thank you for your quick answer, about your function I already saw the define (HEIGHT WITDH) and I tried to modify them but  I found the same results,  at the same time I tried to create my own code unfortunately i hadn't  succeed in this point , could you please send me an example to follow to solve this problem.
Best regard.

**Comment by rkachach** [comment]
I'm sorry but I can't provide examples for this. I'd recommend posting your not working code on stackoverflow.com or opencv grupos and asking for help there.

**Comment by zongoalbert** [comment]
Ok Sir , can you tell me witch file can be  find bounding box object , because i did found it.

**Comment by rkachach** [comment]
Take a look to the blob.cpp it represents the moving blobs along with their bounding boxes. Viewgtk.cpp have a lot of code using them also.

**Comment by zongoalbert** [comment]
HI Sir ,  hope you are doing well . I checked the function  `void calculate_blob_center()` in file `blob.cpp`  ;

and i Used Their returned coordinates to do something like this :

`SrcImage = imread("");` 
`Rect Car_roi = Rect(leftCornerX, leftCornerY, BoxWidth, BoxHeight); `
`Mat Car_roi_image = SrcImage (Car_roi );`
`imwrite("my_path/imageX.png", Car_roi_image);` 
unfortunately also doesn't work , could you please  give me  some indications , Thanks in advance .
